let SingleQuotes = 'How are you';
let DoubleQuotes = "Double quotes ki string";
console.log(SingleQuotes);
console.log(DoubleQuotes);
let char = SingleQuotes.charAt(4);
let ascii = SingleQuotes.charCodeAt(6);
console.log(ascii);
console.log(char);
let subStr = SingleQuotes.substring(2, 11);
console.log(subStr);
let arrStr= SingleQuotes.split("");
let rStr= SingleQuotes.split("o");
let arStr= SingleQuotes.split(" ");
SingleQuotes = SingleQuotes.trim(" ");
// console.log(arrStr);
// console.log(rStr);
// console.log(arStr);
let str=arStr.join("+");
console.log(str);